# Generated by Django 6.0.7 on 2026-08-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcode',
            name='code_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedcode',
            name='code_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedcode',
            name='code_type',
            field=models.CharField(choices=[('single', 'Single Code'), ('compare', 'Compare Code')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='savedcode',
            name='language_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='savedcode',
            name='language_b',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='savedcode',
            name='user_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
