# Generated by Django 6.0.7 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_savedcode_code_a_savedcode_code_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcode',
            name='code_a',
        ),
        migrations.RemoveField(
            model_name='savedcode',
            name='language_a',
        ),
        migrations.RemoveField(
            model_name='savedcode',
            name='user_input',
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='code_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='language_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
