# Generated by Django 6.0.7 on 2026-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_remove_savedcode_code_a_remove_savedcode_language_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcode',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='code_b',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='code_type',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='language_b',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
