# Generated by Django 6.0.7 on 2026-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_savedcode_code_alter_savedcode_code_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcode',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='savedcode',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
